name: az login

on:
  workflow_dispatch:

jobs:
  az-login:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        run: |
          az login --service-principal \
            -u c53d6bbe-834c-424e-b524-5e2d60caf15c \
            -p 9b68Q~LditrAyd0TtKIXy5csC6yWjDLQ4KqDgbuy \
            --tenant 2d23c2c0-6e0f-4c8b-af83-548e0c50f377

      - name: Print Message
        run: echo "Hello World"
